name: test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress test run
        uses: cypress-io/github-action@v5
        with:
          wait-on: 'https://www.google.com/'
          browser: ${{ matrix.browser }}
          group: 'Chrome e2e'
          spec: ./cypress/e2e/**
          config: "baseUrl=https://www.google.com/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}