name: test-variables
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
    container: 
      image: cypress/browsers:node16.16.0-chrome107-ff107-edge
      options: --user 1001
    environment: TEST
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: testing
        env:
          TEST_PRINT: ${{secrets.NOW}}
        run: |
          touch test.json
          echo NOW=${TEST_PRINT} >> test.json
   

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v2
        with:
          name: updated-cypress-env
          path: test.json

      # - name: Set Environment Variables
      #   run: |
      #     echo "API_URL=${{secrets.TEST}}" >> $GITHUB_ENV
      #     echo ${{secrets.TEST.V}}
      #     echo ${{secrets.NOW}}

      # - name: Access Secrets
      #   run: |
      #     echo "API_URL: $API_URL"
      #     echo "CLIENT_USER: $CLIENT_USER"
      #     echo "CLIENT_USER_PASSWORD: $CLIENT_USER_PASSWORD"
