name: test-variables
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
    container: 
      image: cypress/browsers:node16.16.0-chrome107-ff107-edge
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "API_URL=${{secrets.TEST}}" >> $GITHUB_ENV
          echo ${{secrets.TEST}} | sed 's/./& /g'

      - name: Access Secrets
        run: |
          echo "API_URL: $API_URL"
          echo "CLIENT_USER: $CLIENT_USER"
          echo "CLIENT_USER_PASSWORD: $CLIENT_USER_PASSWORD"
